### ISSUE TITLE
Write down idea of project to README

### ISSUE THREAD

**Issue by hyzhak** [botstory/rss-bot#1]
- [x] isn't it dead and gone? Current state of RSS
- [x] list of examples where it is used. Get it here (https://github.com/botstory/rss-bot/issues/5)
- [x] how could you subscribe right now. ➡️  https://github.com/botstory/rss-bot/issues/8
- [x] how messenger could be useful. ➡️ https://github.com/botstory/rss-bot/issues/9
